/*
INSERT INTO BRU_ROLE (ROL_ID, ROL_NAME, ROL_DESCRIPTION) VALUES (999, 'Admin', 'For the admins');
INSERT INTO BRU_ROLE (ROL_ID, ROL_NAME, ROL_DESCRIPTION) VALUES (9999, 'Manager', 'For the managers');
INSERT INTO BRU_ROLE (ROL_ID, ROL_NAME, ROL_DESCRIPTION) VALUES (99999, 'Vendor', 'For the vendors');


INSERT INTO BRU_EMPLOYEE (EMP_ID, EMP_EMAIL, EMP_USERNAME, EMP_FIRST_NAME, EMP_LAST_NAME, EMP_PASSWORD, EMP_IS_ACTIVE, EMP_IS_BLOCKED)
VALUES (888, 'admin@haaga.fi', 'admin', 'Admin', 'Doe', '$2a$10$j02nbolxhxs2AJkp07YmfOxNkXmO0TdsTHnbDdVz6lZgUEVlwgS9S', true, true);

INSERT INTO BRU_EMPLOYEE (EMP_ID, EMP_EMAIL, EMP_USERNAME, EMP_FIRST_NAME, EMP_LAST_NAME, EMP_PASSWORD, EMP_IS_ACTIVE, EMP_IS_BLOCKED)
VALUES (8888, 'manager@haaga.fi', 'manager', 'Manager', 'Doe', '$2a$10$j02nbolxhxs2AJkp07YmfOxNkXmO0TdsTHnbDdVz6lZgUEVlwgS9S', true, true);

INSERT INTO BRU_EMPLOYEE (EMP_ID, EMP_EMAIL, EMP_USERNAME, EMP_FIRST_NAME, EMP_LAST_NAME, EMP_PASSWORD, EMP_IS_ACTIVE, EMP_IS_BLOCKED)
VALUES (88888, 'vendor@haaga.fi', 'vendor', 'Vendor', 'Doe', '$2a$10$j02nbolxhxs2AJkp07YmfOxNkXmO0TdsTHnbDdVz6lZgUEVlwgS9S', true, true);
*/